version: '3.5'
networks:
  workers:
    driver: bridge
services:
  api:
    environment:
     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
     - GOOGLE_CLIENT_REDIRECT=${GOOGLE_CLIENT_REDIRECT}
     - MONGO_DB=${MONGO_DB}
     - MONGO_PASSWORD=${MONGO_PASSWORD}
    image: "mytrade/api"
    ports:
     - "3333:3333"
    restart: always
  web:
    environment:
     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
     - GOOGLE_CLIENT_REDIRECT=${GOOGLE_CLIENT_REDIRECT}
    image: "mytrade/webapp"
    ports:
     - "80:8080"
    restart: always
  manager:
    environment:
     - MONGO_DB=${MONGO_DB}
     - MONGO_PASSWORD=${MONGO_PASSWORD}
     - MANAGER_POLLER_INTERVAL=5
     - HOST=manager
     - NETWORK=docker-infrastructure_workers
    image: "mytrade/manager"
    networks:
     - workers
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  ddns:
    environment:
     - NAMECHEAP_DOMAIN=${NAMECHEAP_DOMAIN}
     - NAMECHEAP_HOSTS=${NAMECHEAP_HOSTS}
     - NAMECHEAP_PASSWORD=${NAMECHEAP_PASSWORD}
    image: "mytrade/ddns"
    restart: always